#   _________________    _____            _________    _______       _______   ____    ____
#  /                /   /    /           / _____  /   / _____ \     / _____ \  \   \  /   /
# /___________     /   /    /           / /    / /   / /    / /    / /    / /   \   \/   /
#            /    /   /    /           / /    / /   / /____/ /    / /____/ /     \      /
#           /    /   /    /           / /    / /   / ______ \    / ______ \       \    /
#          /    /   /    /_______    / /    / /   / /     / /   / /     / /       /   /
#         /    /   /            /   / /____/ /   / /_____/ /   / /_____/ /       /   /
#        /____/   /____________/   /________/   /_________/   /_________/       /___/

#ações
#
#[ACTIONBAR] Manda uma action bar
#[MENSAGEM] Manda uma mensagem
#[TITULO] Manda um título
#[TIT&SUBTIT] Manda um título e um subtítulo (3Use " // " para separar um do outro)
#[BROADCAST] Anuncia para todos.

#[SOM] Manda um som
#"[SOM] ENTITY_EXPERIENCE_ORB_PICKUP, (Volume) 10.0, (Pitch) 10.0"

#[SUMMON] Sumona uma entidade

#[PLAYER] retorna ao player da ação (Funciona fora de ações)

#[ABRIR] Abre um inventário
#[FECHAR] Fecha um inventário

#Lá no arquivo seletores.yml você pode criar um inventário
#Modo de uso: [ABRIR] (id), [FECHAR]

mundos-ativados:
  - "lobby"
  - "world"


EventosDeEntrada:
  ações:
    - "[BROADCAST] &8[&a+&8] &f[PLAYER] entrou no servidor."
    - "[TIT&SUBTIT] &bBem-Vindo // &f[PLAYER]"
    - "[MENSAGEM] &8--------------&7**&8-------------"
    - "[MENSAGEM] &bBem-Vindo &f[PLAYER]"
    - "[MENSAGEM] "
    - "[MENSAGEM] &fSite: &9www.website.com"
    - "[MENSAGEM] &fYT: &4www.youtube.com"
    - "[MENSAGEM] &8--------------&7**&8-------------"
    - "[SOM] ENTITY_EXPERIENCE_ORB_PICKUP, 10.0, 0.0"
    - "[SUMMON] FIREWORK"
    - "[ABRIR] 1"

#Efeitos que serão dados ao jogador o tempo
#inteiro no servidor no mundo do lobby
Efeitos:
  - "JUMP_BOOST, 1"
  - "SPEED, 2"

MensagemDeSaida: "&8[&6-&8] &f[PLAYER] saiu do servidor."

#Feito por DaviXG7, inspiraddo em DeluxeHub,
#nenhum código foi copiado, apenas inspirado!