#   _________________    _____            _________    _______       _______   ____    ____
#  /                /   /    /           / _____  /   / _____ \     / _____ \  \   \  /   /
# /___________     /   /    /           / /    / /   / /    / /    / /    / /   \   \/   /
#            /    /   /    /           / /    / /   / /____/ /    / /____/ /     \      /
#           /    /   /    /           / /    / /   / ______ \    / ______ \       \    /
#          /    /   /    /_______    / /    / /   / /     / /   / /     / /       /   /
#         /    /   /            /   / /____/ /   / /_____/ /   / /_____/ /       /   /
#        /____/   /____________/   /________/   /_________/   /_________/       /___/

#Definir Os itens que serão dados aos jogadores quando
#entrar no lobby e criar.
#Use %player_name% para recolocar o nome do jogador
#Precisa-se do PlaceHolderAPI para isso!

#Cores:
#&0 - Preto           | &9 - Azul
#&1 - Azul escuro     | &b - Ciano
#&2 - Verde escuro    | &9 - Azul
#&3 - Ciano escuro    | &b - Ciano
#&4 - Vermelho escuro | &c - Vermelho
#&5 - Roxo            | &d - Rosa
#&6 - Laranja         | &e - Amarelo
#&7 - Cinza           | &f - Branco

#Opções para as letras:
#&k - Aleatório | &n - Sublinhado
#&l - Negrito   | &o - Itálico
#&m - Traçado   | &r - Reset

#Tudo isso vai funcionar somente no mundo do lobby!

#ações
#
#[ACTIONBAR] Manda uma action bar
#[MENSAGEM] Manda uma mensagem
#[TITULO] Manda um título
#[TIT&SUBTIT] Manda um título e um subtítulo (3Use " // " para separar um do outro)
#[BROADCAST] Anuncia para todos.

#[SOM] Manda um som
#"[SOM] ENTITY_EXPERIENCE_ORB_PICKUP, (Volume) 10.0, (Pitch) 10.0"

#[SUMMON] Sumona uma entidade

#[FLY] Faz o jogador voar

#Só funciona quando o jogador esta com inventário aberto
#[ITEM] Troca o itens do inventário
#ex.: [ITEM] (Slot), (Material), (Nome), (Brilho), (Lore usando " // " entre as linhas)

#[PERMISSÃO] Só faz a ação se tiver permissão
#ex2.: [ABRIR] 1 [PERMISSÃO] sua.permissão
#ex2.: [ABRIR] 1 [!PERMISSÃO] sua.permissão (Caso não tiver a permissão)

#[ABRIR] Abre um inventário
#[FECHAR] Fecha um inventário
#Lá no arquivo seletores.yml você pode criar um inventário
#Modo de uso: [ABRIR] (id), [FECHAR]



#[ABRIR] Abre um inventário
#[FECHAR] Fecha um inventário

#Lá no arquivo seletores.yml você pode criar um inventário
#Modo de uso: [ABRIR] (id), [FECHAR]

mundos-ativados:
  - "lobby"
  - "world"

#Quando você entrar no jogo você da tp para o lobby
tp-quando-entrar: true

#Quando morrer você dá tp pro lobby
tp-quando-morrer: false

aviso-imagem: true

#Coloca tudo no padrão de acordo de sua versão, não mude!
ConfigDefaults: true

#############################################
#ENTRADA E SAÍDA                            #
#############################################

#Quando o jogador entrar tudo que estiver em
#"ações" será executado
EventosDeEntrada:
  acoes:
    - "[TIT&SUBTIT] &bBem-Vindo // &f[PLAYER]"
    - "[MENSAGEM] &8-------------------&7**&8------------------"
    - "[MENSAGEM] &bBem-Vindo &f%player_name%"
    - "[MENSAGEM] "
    - "[MENSAGEM] &fSite: &9www.website.com"
    - "[MENSAGEM] &fYT: &4www.youtube.com"
    - "[MENSAGEM] "
    - "[MENSAGEM] &5&oFeito por DaviXG7"
    - "[MENSAGEM] &8-------------------&7**&8------------------"
    - "[SOM] ENTITY_EXPERIENCE_ORB_PICKUP, 10.0, 0.0"
    - "[SUMMON] FIREWORK"
    - "[ABRIR] 1 [!PERMISSAO] xg7lobby.admin"
    - "[ABRIR] 3 [PERMISSAO] xg7lobby.admin"

#Efeitos que serão dados ao jogador o tempo
#inteiro no servidor no mundo do lobby
Efeitos:
  - "JUMP, 1"
  - "SPEED, 2"

#Mensagens de entrada e de saida

MensagemDeEntrada: "&8[&a+&8] &f%player_name% entrou no servidor."
MensagemDeSaida: "&8[&6-&8] &f%player_name% saiu do servidor."

#############################################
#ANÚNCIOS                                   #
#############################################

anuncios:
  #Cooldown dos anúncios em segundos
  cooldown: 180

  #Anunciar somente no lobby
  ASNL: false

  anuncios:
    anuncio1:
      - "&e&lANÚNCIO:"
      - "&9Esse plugin foi feito por &bDaviXG7"
    anuncio2:
      - "&e&lANÚNCIO:"
      - "&aAvalie o XG7Lobby em &e5 &bestrelas!"
    anuncio3:
      - "&e&lANÚNCIO:"
      - "&fVisite nosso site: &bwww.exemplo.com"



#############################################
#CHAT                                       #
#############################################

#############################################
#LAUNCHPAD                                  #
#############################################

#Só vai funcionar nos mundos do lobby
launchPad:
  ativado: true

  #Caso esteja "true" só será nescessário
  #um bloco para ativar o lauchPad
  #Caso esteja "false" o código vai pular
  #para a parte de baixo onde terá que
  #colocar o bloco de cima e o de baixo
  #para funcionar
  umbloco: true

  #Define se o bloco do lauchpad é
  #uma placa de pressão.
  #(Blocos que você consegue pisar
  #sem estar no chão)
  placadepressao: true

  # Bloco do launchPad
  bloco: STONE_PRESSURE_PLATE

  #Define se o launchPad vai ser definido
  #por dois blocos
  blocodecima: STONE_PRESSURE_PLATE
  blocodebaixo: REDSTONE_BLOCK

  #O jogador será lançado para onde
  #ele estiver olhando
  força: 2
  pulo: 1

  som: "ENTITY_BAT_TAKEOFF, 1.0, 2.0"

#############################################
#DOUBLE JUMP                                #
#############################################

doublejump:
  ativado: true

  #O jogador será lançado para onde
  #ele estiver olhando
  força: 2
  pulo: 1

  cooldown: 2

  som: "ENTITY_BAT_TAKEOFF, 1.0, 2.0"

#############################################
#MOTD                                       #
#############################################

#MOTD é a mensagem que aparece antes de
#entrar no servidor!
motd:
  ativado: true

  texto:
    - "&9XG7&3Lob&bby&r"
    - "&5&oFeito por DaviXG7"

#############################################
#SCORES                                     #
#############################################

scores:
  #Ticks de atualização da score

  atualizacao: 5

  tablist:

    ativado: true

    cabecalho:
      - "&9X&3G7&bLobby"
      - "&7Feito por DaviXG7"
      - ""

    rodape:
      - ""
      - "&9Visite nosso site: &bsite.com"

  scoreboard:

    ativado: true

    titulo: "&9X&3G7&bLobby"

    linhas:
      - " "
      - "&e&lJogador&f:"
      - "&7Nome: &9%player_name%"
      - "&7Rank: &r%luckperms_prefix%"
      - "  "
      - "&7Jogadores online: &a%server_online%"
      - ""
      - "&8www.exemplo.com"


  #SÓ FUNCIONA +1.9
  bossbar:

    ativado: true

    #Os placeholders não funcionam aqui
    título: "&9&lBem-vindo ao servidor"

    #Veja aqui todas as cores
    #https://helpch.at/docs/1.16.5/org/bukkit/boss/BarColor.html
    cor: BLUE

    #Veja aqui todos os estilos
    #https://helpch.at/docs/1.16.5/org/bukkit/boss/BarStyle.html
    estilo: SOLID

    #Vai de 0 a 1. Por exemplo: 0.5
    progresso: 1

#############################################
#OPÇÕES DO JOGADOR                          #
#############################################

#Geral
CancelarMortePeloVoid: true
PerderPontosDeComida: false

#Danos

#Caso esteja "false", TODOS os tipos de dano
#vão ser cancelados, se estiver "true", caso
#algumas da de baixo estiver false somente
#aquela opção vai ser cancelada!
LevarDanos: false

#Permite se a pessoa vai atacar,
#Se "LevarDanoPorAtaque" estiver
#falso, O jogador só poderá atacar
#mobs
Ataque: false

LevarDanoPorAtaque: false
LevarDanoPorSufocamento: false
LevarDanoPorAfogamento: false
LevarDanoPorQueda: false
#Ejetores, tnts, etc, mas são todos.
LevarDanoPorBlocos: false
LevarDanoPorMagma: false
LevarDanoPorLava: false
LevarDanoPorFogo: false
LevarDanoPorBlocoCaindo: false
#Geralmente por Élitro
LevarDanoPorColisão: false
LevarDanoPorExplosão: false

#Interação

#Apenas jogadores que tiver a permissão
#Vão quebrar blocos e colocar
QuebrarBlocos: false
ColocarBlocos: false
InteragirComBlocos: false

#Drop, pegar

PegarItens: true
JogarItens: false

#############################################
#OPÇÕES DE MUNDO                            #
#############################################

#Define se mobs vão spawnar no lobby
MobSpawn: false

#Define o ciclo do clima no lobby
CicloDaChuva: false

#SÓ VAI SER APLICADO QUANDO ALGUM JOGADOR ENTRAR!
#Define o ciclo do dia e o tempo do mundo
CicloDoDia: false

#Nascer do Sol: 0
#Meio-dia: 6000
#Pôr do Sol: 13000
#Meia-noite: 18000
TempoDoDia: 6000

#Define se as folhas vão cair no lobby
FolhasCaindo: false

#Define se os blocos vão queimar no lobby
QueimaDeBlocos: false

#Cancelar explosões
CancelarExplosões: true
